---
- name: Configure RouterOS proxy
  hosts: "{{ mtip }}"
  gather_facts: false
  tasks:
    - name: Set ip store proxy
      community.routeros.command:
        commands:
          - /ip proxy set cache-path=web-proxy1 enabled=yes max-cache-size=10000KiB src-address="{{ mtip }}"
          - /ip proxy access remove numbers=0
          - delay 1s
          - /ip proxy access remove numbers=1
          - delay 1s
          - /ip proxy access remove numbers=2
          - delay 1s
          - /ip proxy access remove numbers=0
          - delay 1s
          - /ip proxy access remove numbers=1
          - delay 1s
          - /ip proxy access remove numbers=2
          - delay 1s
          - /ip proxy access remove numbers=0
          - delay 1s
          - /ip proxy access remove numbers=1
          - delay 1s
          - /ip proxy access remove numbers=2
          - delay 5s
          - /ip proxy access add src-address="{{ service_ip }}" action=allow
          - delay 5s
          - /ip proxy access add action=deny
      register: proxyset